[tool.poetry]
name = "project-name"  # FIXME
version = "0.1.0"
description = "A short description of your package."  # FIXME
authors = ["ankandrew <61120139+ankandrew@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.group.test.dependencies]
pytest = "*"

[tool.poetry.group.dev.dependencies]
mypy = "*"
ruff = "^0.3.1"

[tool.ruff]
line-length = 100
target-version = "py310"

[tool.ruff.lint]
# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

[tool.ruff.format]
line-ending = "lf"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
