name: Security Scan
on:
  push:
#  schedule:
#    - cron: '0 0 * * 0' # Weekly
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Safety
        run: pip install safety

      - name: Run Safety Scan
        run: safety check --full-report
